blank_issues_enabled: false

contact_links:
  - name: Check the Sphere-aae Documentation
    url: https://llm.sphere_aae.ai/docs/
    about: Our documentation might provide answers to your questions.
  - name: Chat on Discord
    url: https://discord.gg/9Xpy2HGBuD
    about: Join the Discord Server to live chat with the community.
